[package]
name = "shortpath"
version = "0.2.3"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
gumdrop = "0.6.0"
serde_json = "1.0.40"
lexical_bool = "0.1.1"

[profile.release]
lto = true
panic = "abort"
