[package]
name = "shortpath"
version = "0.2.4"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[[bin]]
name = "shortpath"
path = "src/bin/main.rs"

[dependencies]
gumdrop = "0.7.0"
serde_json = "1.0.44"
lexical_bool = "0.1.3"

[profile.release]
lto = true
panic = "abort"
